# This is an example mod metadata file for NeoForge.
# It is expected to be placed in META-INF/neoforge.mods.toml

# The license for your mod. This is mandatory metadata and allows for easier
# comprehension of your redistributive properties.
license="${mod_license}"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/mattbillpage/quantumboots/issues"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]

# The modid of the mod
modId="${mod_id}"

# The version number of the mod
version="${mod_version}"

# A display name for the mod
displayName="${mod_name}"

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/mattbillpage/quantumboots"

# A file name in the root of the mod JAR containing a logo for display
iconFile="icon.png"

# Prevent the logo from being blurred when displayed
logoBlur=false

# A text field displayed in the mod UI
#credits=""

# The authors of the mod, displayed in the mod UI
authors="mattbillpage"

# The description text for the mod (multi line!)
description='''
Armour overhaul mod inspired by BTA
'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
#[[mixins]]
#config="${mod_id}.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from
# META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"


# NeoForge dependency
[[dependencies.${mod_id}]]

    # The modid of the dependency
    modId="neoforge"

    # The type of dependency
    type="required"

    # The version range of the dependency
    versionRange="[${neo_version},)"

    # An ordering relationship between this mod and the dependency
    ordering="NONE"

    # Side this dependency is applied on
    side="BOTH"


# Minecraft dependency
[[dependencies.${mod_id}]]

    modId="minecraft"

    # This version range declares the supported Minecraft version
    versionRange="${minecraft_version_range}"

    ordering="NONE"

    side="BOTH"


# Features are specific properties of the game environment that you may
# want to declare you require. They are side aware.
#[features.${mod_id}]
#openGLVersion="[3.2,)"